services:
  app:
    build: .
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://goals:example@db:5432/goals
      - MAIL_URL=smtp://mailer:1025
      - MAIL_FROM=no-reply@example.com
      - MAIL_FROM_TITLE="Financial Goals"
      - SESSION_SECRET=example-session
    ports:
      - "3000:3000"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: goals
      POSTGRES_PASSWORD: example
      POSTGRES_DB: goals
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
volumes:
  db: ~
